### ISSUE TITLE
firebase.messaging().requestPermission() does nothing on android

### ISSUE THREAD

**Issue by VilleMiekkoja** [invertase/react-native-firebase-docs#241]
Push notification permissions are automatically requested during installation for android.

The method requestPermission() does not open the permission prompt, atleast not on android. It seems to always resolve the promise, regardless of the case.

**Comment by mikehardy** [comment]
You are neither proposing a direct problem with the documentation nor proposing a change, so I don't see an issue

requestPermission() is required in order to ask the operating system (on iOS) to *listen* for messages as well on v5

**Comment by VilleMiekkoja** [comment]
The docs are wrong in here: https://github.com/invertase/react-native-firebase-docs/blob/master/docs/messaging/receiving-messages.md:

"If the user has not already granted permissions, then you can prompt them to do so, as follows:

try {
    await firebase.messaging().requestPermission();
    // User has authorised
} catch (error) {
    // User has rejected permissions
}
"

That is not true on Android. If user has not granted the permission, this does not prompt them to do so.

**Comment by mikehardy** [comment]
On android it always resolves to true, because android doesn't require permission.

It is however still a requirement in order to listen for messages in the background as that's the signal in v5 to attach a listener.

On iOS if the user has already granted permission or the user has blocked permission they won't get a prompt either.

My suggestion at this point?

- propose a PR that indicates requestPermission is required in order to listen for messages
- include in that PR a recommendation to use `react-native-permissions` to do the actual permission management (it's a much better module for it, including for blocked permission handling etc), and only after you have permissions where you want them call requestPermission (which at that point can just be thought of as "register on native side to listen for messages"

If you hit the edit button on the top right and cooked something up, we could get it merged

**Comment by VilleMiekkoja** [comment]
But android does have the notification permission options for that in settings. I used library https://github.com/riwu/react-native-open-notification to open the permission settings. Are you saying that it doesn't matter whether the user has allowed notifications on android, that he will receive those anyway? I thought the user agrees on the permissions during installation. But then he can deny that permission later on. And if he has denied those permissions, then one could think from these docs that calling requestPermissions() would prompt them to do so. So the quick hotfix for the docs is to modify that sentence. 

I tested and you are not required to requestPermission() in order to get notifications. Even when the app is closed, you will get notifications without calling requestPermission.

**Comment by VilleMiekkoja** [comment]
https://github.com/invertase/react-native-firebase-docs/pull/242

**Comment by mikehardy** [comment]
on Android? What versions tested? on iOS? what versions.

All of this stuff changes every API it seems. You must be specific.

**Comment by VilleMiekkoja** [comment]
Android 8.1.0, Nexus 6P. Kernel version: 3.10.73-g7bf0310 (gcc version 4.9.x-google 20140827 (prerelease) /GCC)). android-build@abfarm245 #1. Made on Thur Mar 15 22:25:39 UTC 2018. Also tested on android emulator too, Nexus 5.

**Comment by mikehardy** [comment]
Try an Android 10 emulator with react-native-permissions requestNotification vs react-native-firebase requestPermission - I think it'll pop a permission dialog in react-native-permissions because it's permission implementation is more up to date than react-native-firebase v5

That said, react-native-firebase 5.2.5 is not deployable I don't think. firebase apps will crash with pods lower than 6.5 on ios13+, which implies react-native-firebase 5.5+ series, and react-native-firebase 5.5+

**Comment by VilleMiekkoja** [comment]
Ok, so you mean I should update to atleast 5.5? If I remember right that requires newer version of react-native also -> need to update that too. Don't wanna to that unless no other option, since every update process of react-native has been very painful.

**Comment by mikehardy** [comment]
Understood - react-native 0.58 to 0.59 was not so bad at least, although 0.59 to 0.60 is a HUGE leap, with 0.61 then being tiny again. Not sure if these are your exact versions but the upgrade helper dialed in from where you are to where you want to go is very very useful: https://react-native-community.github.io/upgrade-helper/?from=0.58.6&to=0.59.10

**Comment by wincod75** [comment]
Any update on this one? I'm on RN 59, noticed the same issue, iOS prompts for notifications, Android does not, but auto defaults to true. Using RNFB V5.

**Comment by mikehardy** [comment]
Use react-native-permissions if at all possible. It is by far the best way to manage permissions as it is focused on that, whereas here it is naturally just an afterthought
